### ISSUE TITLE
SingleTableInheritance should not filter out pivot attributes

### ISSUE THREAD

**Issue by JFossey** [Nanigans/single-table-inheritance#29] opened 2016-10-03 09:52 UTC
Thanks for a great package, we have started to use it a lot.

Recently we have run into a problem when using Single Table Inheritance with Eloquent eager loading.

If I run the below I would get the **expected results**.

``` php
$model = new App\MyModel;
$model = $model->find(1);
dd($model->myRelation);
```

If I run the below I would get an **empty result**.

``` php
$model = new App\MyModel;
$model = $model->with('myRelation')->find(1);
dd($model->myRelation);
```

After some digging I found that it worked when there was no Single Table Inheritance.

This lead me to find that `SingleTableInheritanceTrait::setFilteredAttributes()` was stripping the pivot table attributes add by the relation.

`$attributes` before filtering.

```
Array
(
    [id] => 21
    [type] => sub_type
    [user_id] => 1
    [name] => Test Information
    [description] =>     
    [status] => true
    [created_at] => 2016-10-01 10:56:39
    [updated_at] => 2016-10-01 10:56:39
    [pivot_parent] => 6
    [pivot_other_id] => 21
    [pivot_extra] => 0
)
```

`$attributes` after filtering.

```
Array
(
    [id] => 21
    [type] => sub_type
    [user_id] => 1
    [name] => Test Information
    [description] =>     
    [status] => true
    [created_at] => 2016-10-01 10:56:39
    [updated_at] => 2016-10-01 10:56:39
)
```

All pivot attributes are added with the hard coded prefix `pivot_`. The below code works for me.

``` diff
  public function setFilteredAttributes(array $attributes) {
    $persistedAttributes = $this->getPersistedAttributes();
    if (empty($persistedAttributes)) {
      $filteredAttributes = $attributes;
    } else {
      // The query often include a 'select *' from the table which will return null for columns that are not persisted.
      // If any of those columns are non-null then we need to filter them our or throw and exception if configured.
      // array_flip is a cute way to do diff/intersection on keys by a non-associative array
      $extraAttributes = array_filter(array_diff_key($attributes, array_flip($persistedAttributes)), function($value) {
        return !is_null($value);
      });
      if (!empty($extraAttributes) && $this->getThrowInvalidAttributeExceptions()) {
        throw new SingleTableInheritanceInvalidAttributesException("Cannot construct " . get_called_class() . ".", $extraAttributes);
      }

      $filteredAttributes = array_intersect_key($attributes, array_flip($persistedAttributes));
    }
+
+    // All pivot attributes start with 'pivot_'
+    // Add pivot attributes back in
+    $filteredAttributes += $this->getPivotAttributeNames($attributes);

    $this->setRawAttributes($filteredAttributes, true);
  }

+  protected function getPivotAttributeNames($attributes)
+  {
+    $pivots = [];
+    foreach ($attributes as $key => $value) {
+      if (starts_with($key, 'pivot_')) {
+        array_set($pivots, $key, $value);
+      }
+    }
+    return $pivots;
+  }
```

Alternatively you  could documenting that when eager loading is used and if a relation adds pivot properties using the withPivot() method then all all keys and additional properties need to be added to the `$persisted` array property.

My preference would be to not filter out `pivot_*` properties.

**Comment by bostanio** [comment] 2016-10-03 11:35
Its not clear from you example what `pivot` even is. Perhaps you can expand your example of better yet submit the pull request with a failing test case.

**Comment by JFossey** [comment] 2016-10-03 13:42
Sorry for the poor explanation, I probably should have led with the fact that this happens for a Many to many relationship using the eloquent belongsToMany() relation method.

The pivot is the associative table and eloquent internally seems to uses model attributes keyed with `pivot_column_name` to keep track of the properties used in a relation.

## Ref:
* [Docs](https://laravel.com/docs/5.2/eloquent-relationships#many-to-many)
* [Pivot Model - Illuminate/Database/Eloquent/Relations/Pivot](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Eloquent/Relations/Pivot.php)
* [Get Pivot Columns - Illuminate/Database/Eloquent/Relations/BelongsToMany](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php#L426)
* [Where on Pivot - Illuminate/Database/Eloquent/Relations/BelongsToMany](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php#L124)

**Comment by bostanio** [comment] 2016-10-04 00:47
PR with a failing test would be ideal.

**Comment by JFossey** [comment] 2016-10-04 07:04
I will see if I can put together a test, but it might be little while.

**Comment by EdouardNaze** [comment] 2017-11-01 19:27
Thanks for your message, i spend one day looking though all my code because i can't find why my pivot array was empty. Pivot keys should really be persisted by default.

**Comment by patricknazar** [comment] 2018-02-07 01:51
I believe this is the cause of #41 as @JFossey says

**Comment by bostanio** [comment] 2019-03-17 02:48
@JFossey you had the right approach. It took a while but now fixed.

**Closed by bostanio** 2019-03-17 02:48 UTC
